version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: compare_machine_postgres
    environment:
      POSTGRES_DB: compare_machine_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
